#!/bin/sh

JRUBY_VERSION="1.5.5"

HERE=$(cd "`dirname "$0"`" && pwd)


if [ ! -d "$HERE/../tools/gems" ]; then
  mkdir -p "$HERE/../tools/gems"
fi

export GEM_HOME=$(cd $HERE/../tools/gems && pwd)
export GEM_PATH=$GEM_HOME

exec $HERE/../tools/jruby-$JRUBY_VERSION/bin/jruby $@

